config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "categories#index"
  resources :categories do
    resources :comments, only: %i[create update destroy]
  end
  resources :photos do
    resources :comments, only: %i[create update destroy]
  end
  get "/search", to: "photos#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true,
                   uniqueness: true
  validates :description, presence: true,
                          length: { in: 10..240 }
  # validates :cover, presence: true

  has_many :comments, as: :commentable, dependent: :nullify
  has_many :photos, dependent: :nullify
  has_one_attached :cover
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true,
                   length: { in: 2..350 }

  belongs_to :photo, optional: true, counter_cache: true
  belongs_to :commentable, polymorphic: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true,
                          length: { in: 20..240 }
  # validates :image, presence: true

  belongs_to :category, optional: true, counter_cache: true
  has_many :comments, as: :commentable, dependent: :destroy
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/:id
  def show
    @category = Category.find(params[:id])
    @photos = @category.photos
    @comment = @category.comments
    @comment_new = Comment.new
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories
  def create
    @category = Category.new(category_params)
    
    if @category.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /categories/id/edit
  def edit
    @category = Category.find(params[:id])
  end

  # PATCH/PUT /departments/:id
  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/:id
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    
    redirect_to categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :cover) 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # POST /categories/:category_id/comments
    # POST /photos/:photo_id/comments
    def create
        if params[:category_id]
            @category = Category.find(params[:category_id])
            comment = @category.comments.new(comment_params)
        elsif params[:photo_id]
            @photo = Photo.find(params[:photo_id])
            comment = @photo.comments.new(comment_params)
        end

        if comment.save   
          if params[:category_id]
            redirect_to category_path(@category)
          elsif params[:photo_id]
            redirect_to photo_path(@photo)
          end   
        else
            redirect_to category_path(@category)
        end
    end

    def destroy
        comment = Comment.find(params[:id])
        if params[:category_id]
            category = Category.find(params[:category_id])
            comment = category.comments.find(params[:id])
        elsif params[:photo_id]
            photo = Photo.find(params[:photo_id])
            comment = photo.comments.find(params[:id])
        end

        comment.delete
        render json: nil, status: :no_content
    end

    def update
        comment = Comment.find(params[:id])
        if params[:category_id]
            category = Category.find(params[:category_id])
            comment = category.comments.find(params[:id])
        elsif params[:photo_id]
            photo = Photo.find(params[:photo_id])
            comment = photo.comments.find(params[:id])
        end

        if comment.update(comment_params)
            render json: comment
        else
            render json: { errors: comment.errors.full_messages }, status: :unprocessable_entity
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    # GET /photos/:id
    def show
      @photo = Photo.find(params[:id])
      @comments = @photo.comments
      @comment_new = Comment.new
    end
  
    # GET /photos/new
    def new
      @photo = Photo.new
      @category = Category.find(params[:category_id])
    end
  
    # POST /photos
    def create
      @photo = Photo.new(photo_params)
      @category = @photo.category
      
      if @photo.save
        redirect_to category_path(@photo.category)
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    # GET /categories/id/edit
    def edit
      @photo = Photo.find(params[:id])
      @category = Category.find(params[:category_id])
    end
  
    # PATCH/PUT /departments/:id
    def update
      @photo = Photo.find(params[:id])
      @category = @photo.category

      if @photo.update(photo_params)
        redirect_to category_path(@photo.category)
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    # DELETE /categories/:id
    def destroy
      @photo = Photo.find(params[:id])
      @category =  @photo.category
      @photo.destroy
      
      redirect_to category_path(@category), status: :see_other
    end

    def search
      query = params[:query].downcase
      @photos = Photo.where("LOWER(title) LIKE ?", "%#{query}%")
      render "search"
      # @photos = Photo.all
    end

    private
  
    def photo_params
      params.require(:photo).permit(:title, :description, :category_id, :image) 
      # :description, :category_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/categories/_comments.html.erb
<div class="my-1">
  <%= form_with url: category_comments_path(@category), model: comment do |form| %>
    <div class="mb-0.5">
      <%= form.text_area :body, placeholder: "Some respectul commet here.", class: "input" %>
      <% comment.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit  class: "button button--secondary overline btn-width100" %>
    </div>
  <% end %>
</div>

<div>
  <h3 class="head-xs mb-1.5">Comments</h3>
  <div class="mx-0.5">
    <% @comment.each do |comment| %>
        <div class="comment--card">
            <div class="comment--card__header">
                <p class="text-md"><%= comment.body%></p>
            </div>
            <div class="comment--card__footer">
              <p class="text-transform-capitalize"><%= time_ago_in_words(comment.created_at) %></p>
              <button class="comment--card__button-trash">
                <%= link_to category_comment_path(@category, comment), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } do %>
                      <%= image_tag("trash.png")%>
                  <% end %>
              </button>
            </div>
        </div>
    <%end%>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <% unless category.errors.full_messages.empty? %>
    <div class="category--form__section">
      <h2 class="head-xs category--form__header-error">Something went wrong</h2>
      <ul class="m-0">
        <%category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <%end%>
      </ul>
    </div>
  <%end%>
  <div class="category--form__section">
    <%= form.label :name,  class: "category--form__label" %>
    <%= form.text_field :name, placeholder: "Technology", class: "category--form__input" %>
  </div>
  <div class="category--form__section">
    <%= form.label :description, class: "category--form__label" %>
    <%= form.text_area :description, placeholder: "Exploring our complicated relationship with technology...", class: "category--form__textarea" %>
  </div>
  <div class="category--form__section">
    <%= form.label :cover, class: "category--form__label" %>
    <%= form.file_field :cover, accept: "image/png, image/jpeg" %>
  </div>
  <div class="category--form__section">
    <%= form.submit class: "button--create category--form__button" %>
  </div>
<% end %>
  <button class="button--default category--form__button"> <%= link_to 'Back', categories_path, class: "text-decoration-none text-stone" %> </button>

app/views/categories/edit.html.erb
<section class="section-sm">
    <div class="container-md">
        <h1>Edit category</h1>
        <%= render "form", category: @category  %>
    </div>
</section>

app/views/categories/index.html.erb
<section class="section-sm">
  <div class="container-sm categories">
    <h1 class="ctg-title">Categories</h1>

    <button class="button button--secondary button--sm ctg-bot-margin "><%= link_to "NEW CATEGORY", new_category_path, class: "ctg-button" %></button>
    <!--<%= button_tag "New category", type: "button"%>-->

    <% @categories.each do |category| %>
      <div class="ctg-card">
          <div>
            <% if category.cover.attached? %>
              <%= link_to category_path(category) do%>
              <%= image_tag category.cover, class: "ctg-cover"%>
              <% end %>
            <%end%>
          </div>
          <div class="ctg-card-body">
            <h2 class="card-title"><%= category.name %></h2>
            <p class="card-counter"><%= "#{category.photos_count} photos" %></p>
            <p class="card-description"><%= category.description %></p>
          </div>
          <div class="ctg-card-footer">
            <button class="button round-btn">
            <%= link_to edit_category_path(category) do%>
            <%= image_tag("pen.png")%>
            <% end %>
            </button>
            <button class="button round-btn">
            <%= link_to category_path(category), data: {
              turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      } do %>
            <%= image_tag("trash.png")%>
            <% end %>
            </button>
          </div>
       </div>
    <%end%>
  </div>
</section>

app/views/categories/new.html.erb
<section class="section-sm">
    <div class="container-sm">
        <h1 class="head-md category--form__header">New category</h1>
        <%= render "form", category: @category  %>
    </div>
</section>

app/views/categories/show.html.erb
<section class="section-sm">
    <div class="container-sm">
        <h1 class="ctg-title"><%= @category.name %></h1>
        <p class="ctg-description"><%= @category.description %></p>

        <!-- Change new_employee_path after creating employee routes -->
        <button class="button button--secondary button--sm ctg-bot-margin"><%= link_to "NEW PHOTO", new_photo_path(category_id: @category.id), class: "ctg-button" %></button>
        <% @photos.each do |photo| %>
            <div class="ctg-card gray-card">
                <% if photo.image.attached? %>
                    <div>
                        <%= link_to photo_path(photo) do%>
                            <%= image_tag photo.image, class: "img-cover"%>
                        <% end %>
                    </div>
                <% end %>
                <div class="ctg-card-body">
                    <h3 class="card-title"><%= photo.title %></h3>
                <div class="card-wrapper">
                    <p class="card-counter"><%= "#{photo.comments_count} Comments" %></p>
                        <div class="imgs-card-footer">
                            <button class="button round-btn">
                                <%= link_to edit_photo_path(photo, category_id: @category.id) do%>
                                    <%= image_tag("pen.png")%>
                                <% end %>
                            </button>
                             <button class="button round-btn">
                                <%= link_to photo_path(photo), data: {
                                                turbo_method: :delete,
                                                turbo_confirm: "Are you sure?" } do %>
                                     <%= image_tag("trash.png")%>
                                 <% end %>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
                    
        <%= render "comments", comment: @comment_new %>

    </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div>
      <p>Build with ♥ by</p>
      <p>Alex Mamani💻 Dave💻 </p>
      <p>Frank Cano💻 Kevin Lopez💻</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div>
    <%= link_to image_tag("logo.png"), categories_path %>
  </div>
  <div>
    <button class="button"><%= link_to "SEARCH", photos_path, class: "navbarbutton" %></button>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Somesplash C6 Week 09 Team 7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/photos/_comments.html.erb
<div class="my-1">
    <%= form_with url: photo_comments_path(@photo), model: comment do |form| %>
        <div class="mb-0.5">
            <%= form.text_area :body, placeholder: "Some respectful comment here.", class: "input"%>
            <% comment.errors.full_messages_for(:body).each do |message| %>
                <div><%= message %></div>
            <%end%>
        </div>

        <div>
          <%= form.submit class: "button button--secondary overline btn-width100" %>
        </div>
    <% end %>
</div>

<div>
    <h3 class="head-xs mb-1.5">Comments</h3>
    <div class="mx-0.5">
        <% @comments.each do |comment| %>
            <div class="comment--card">
                <div class="comment--card__header">
                    <p class="text-md"><%= comment.body%></p>
                </div>
                <div class="comment--card__footer">
                    <p class="text-transform-capitalize"><%= time_ago_in_words(comment.created_at) %></p>
                    <button class="comment--card__button-trash">
                        <%= link_to photo_comment_path(@photo, comment), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                        } do %>
                            <%= image_tag("trash.png")%>
                        <% end %>
                    </button>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/photos/_form.html.erb
    <%= form_with model: photo, class: "gap-4 flex flex-column"  do |form| %>
    <div class="b-16">
        <%# Something went wrong: %>
        <% unless photo.errors.full_messages.empty? %>
                <div class="text-sm b-16">
                    <h2 class="head-xs text-red">Something went wrong:</h2>
                    <ul class="m-0">
                        <% photo.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
        <%end%>
        <%# FIN:Something went wrong: %>
        <div class="b-16">
            <%= form.label :title, class:"overline"%>
            <%= form.text_field :title, class:"input", placeholder: "Big montain" %>
        </div>

        <div class="b-16">
            <%= form.label :description, class:"overline"%>
            <%= form.text_area :description, class:"input", placeholder: "Photo taken on..." %>
        </div>

        <div class="b-16">
            <%= form.label :category_id, class:"overline" %>
            <%= form.collection_select :category_id, Category.order(:name), :id, :name, { selected: category.id }, class:"input" %>
        </div>
        
        <div class="b-16">
            <%= form.label :image, class:"overline text-decoration-none" %>
            <%= form.file_field :image, class:"button button--lg btn-width100 overline text-decoration-none", accept: "image/png, image/jpeg"%>
        </div>

        <div>
            <%= form.submit class:"button button--secondary btn-width100 overline"  %>
        </div>
    </div>
        <div class="b-16">
            <button class="button button--default btn-width100 overline"> <%= link_to 'Back', categories_path, class: "gray-700 text-decoration-none" %> </button>
        </div>
    <% end %>

app/views/photos/edit.html.erb
<section class="section-sm">
    <div class="container-sm">
        <h1 class="head-md category--form__header">Edit photo</h1>
        <%= render "form", photo: @photo, category: @category %>
    </div>
</section>

app/views/photos/index.html.erb
<section class="section-sm expand">
  <div class="container-sm">
    <div class="search">
      <h1 class="head-md semibold">Search</h1>
      <div class="search">
        <%= form_with url: "/search", method: :get do |form| %>
            <% form.label :query %>
            <%= form.text_field :query, placeholder: "search", class:"search input" %>
            <%= form.submit "SEARCH PHOTOS", class:"index-button button button--secondary btn-width100 overline b-16"  %>
          <% end %>
      </div>
    </div>
  </div>
</section>

app/views/photos/new.html.erb
<section class="section-sm">
    <div class="container-sm">
        <h1 class="head-md category--form__header">New Photo</h1>
        <%= render "form", photo: @photo, category: @category%>
    </div>
</section>

app/views/photos/search.html.erb
<section class="section-sm">
  <div class="container-sm">
    <% @photos.each do |photo| %>
        <div class="search--block">
            <% if photo.image.attached? %>
                <div>
                <%= link_to photo_path(photo) do%>
                  <%= image_tag photo.image, class:"search--img ctg-cover"%>
                <% end %>
                </div>
            <% end %>
            <div class="search--card">
              <h2 class="head-xs"><%= photo.title %>:</h2>
              <div class="search--card__footer">
                <div class="mb-0.25">
                  <p class="text-sm regular gray"><%= photo.comments_count %> comments</p>
                </div>
                <div class="search--card__buttons">
                  <button class="button round-btn">
                    <%= link_to edit_photo_path(photo) do %>
                      <%= image_tag("pen.png")%>
                    <% end %>
                  </button>
                  <button class="button round-btn">
                  <%= link_to photo_path(photo), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                      } do %>
                      <%= image_tag("trash.png") %>
                    <% end %>
                  </button>
                </div>
              </div>
            </div>
        </div>
    <% end %>
  </div>
</section>  

app/views/photos/show.html.erb
<section class="section-sm">
    <div class="container-sm">
        <h1 class="img-title"> <%= @photo.title %> </h1>
        <p class="img-description"> <%= @photo.description %> </p>
        <p class="img-counter"> <%= "Updated at #{@photo.updated_at.strftime("%B %e, %Y")}" %> </p>
        <% if @photo.image.attached? %>
            <div>
                <%= image_tag @photo.image%>
            </div>
        <% end %>
    <%= render "comments", comment: @comment_new %>
    </div>

</section>